# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
  displayName: 'Execute Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  displayName: 'Execute Test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
  displayName: 'Execute Publish'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'LuisDev'
    appType: 'webAppLinux'
    WebAppName: 'eduardodorr-devfreela-azure-devops'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|7.0'
  displayName: 'Execute Deploy'